from Element import Element

h = Element("Hydrogen", "H", 1.01)
he = Element("Helium", "He", 4.00)
li =  Element("Lithium", "Li", 6.94)
be =  Element("Beryllium", "Be", 9.01)
b =  Element("Boron", "B", 10.8)
c =  Element("Carbon", "C", 12.0)
n =  Element("Nitrogen", "N", 14.0)
o =  Element("Oxygen", "O", 16.0)
f =  Element("Fluorine", "F", 19.0)
ne =  Element("Neon", "Ne", 20.2)

na =  Element("Sodium", "Na", 23.0)
mg =  Element("Magnesium", "Mg", 24.3)
al =  Element("Aluminium", "Al", 27.0)
si =  Element("Silicon", "Si", 28.1)
p =  Element("Phosphorus", "P", 31.0)
s =  Element("Sulfur", "S", 32.1)
cl =  Element("Chlorine", "Cl", 35.5)
ar =  Element("Argon", "Ar", 40.0)
k =  Element("Potassium", "K", 39.1)
ca =  Element("Calcium", "Ca", 40.1)

sc =  Element("Scandium", "Sc", 45.0)
ti =  Element("Titanium", "Ti", 47.9)
v =  Element("Vanadium", "V", 50.9)
cr =  Element("Chromium", "Cr", 52.0)
mn =  Element("Manganese", "Mn", 54.9)
fe =  Element("Iron", "Fe", 55.9)
co =  Element("Cobalt", "Co", 58.9)
ni =  Element("Nickel", "Ni", 58.7)
cu =  Element("Copper", "Cu", 63.6)
zn =  Element("Zinc", "Zn", 65.4)

ga =  Element("Gallium", "Ga", 69.7)
ge =  Element("Germanium", "Ge", 72.6)
ars =  Element("Arsenic", "As", 74.9)
se =  Element("Selenium", "Se", 79.0)
br =  Element("Bromine", "Br", 79.9)
kr =  Element("Krypton", "Kr", 83.8)
rb =  Element("Rubidium", "Rb", 85.5)
sr =  Element("Strontium", "Sr", 87.6)
y =  Element("Yttrium", "Y", 88.9)
zr =  Element("Zirconium", "Zr", 91.2)

nb =  Element("Niobium", "Nb", 92.9)
mo =  Element("Molybdenum", "Mo", 96.0)
tc =  Element("Technetium", "Tc", 98.0)
ru =  Element("Ruthenium", "Ru", 101.1)
rh =  Element("Rhodium", "Y", 88.9)
pd =  Element("Palladium", "Zr", 91.2)
ag =  Element("Silver", "Nb", 92.9)
cd =  Element("Cadmium", "Mo", 96.0)
ind =  Element("Indium", "Tc", 98.0)
sn =  Element("Tin", "Ru", 101.1)

sb =  Element("Antimony", "Sb", 121.8)
te =  Element("Tellurium", "Te", 127.6)
i =  Element("Iodine", "I", 126.9)
xe =  Element("Xenon", "Xe", 131.3)
cs =  Element("Cesium", "Cs", 132.9)
ba =  Element("Barium", "Ba", 137.3)
la =  Element("Lanthanum", "La", 138.9)
ce =  Element("Cerium", "Ce", 140.1)
pr =  Element("Praseodymium", "Pr", 140.9)
nd =  Element("Neodymium", "Nd", 144.2)

pm =  Element("Promethium", "Pm", 145.0)
sm =  Element("Samarium", "Sm", 150.4)
eu =  Element("Europium", "Eu", 152.0)
gd =  Element("Gadolinium", "Gd", 157.3)
tb =  Element("Terbium", "Tb", 158.9)
dy =  Element("Dysprosium", "Dy", 162.5)
ho =  Element("Holmium", "Ho", 164.9)
er =  Element("Erbium", "Er", 167.3)
tm =  Element("Thulium", "Tm", 168.9)
yb =  Element("Ytterbium", "Yb", 173.0)

lu =  Element("Lutetium", "Lu", 175.0)
hf =  Element("Hafnium", "Hf", 178.5)
ta =  Element("Tantalum", "Ta", 180.9)
w =  Element("Tungsten", "W", 183.8)
re =  Element("Rhenium", "Re", 186.2)
os =  Element("Osmium", "Os", 190.2)
ir =  Element("Iridium", "Ir", 192.2)
pt =  Element("Platinum", "Pt", 195.1)
au =  Element("Gold", "Au", 197.0)
hg =  Element("Mercury", "Hg", 200.6)

tl =  Element("Thallium", "Tl", 204.4)
pb =  Element("Lead", "Pb", 207.2)
bi =  Element("Bismuth", "Bi", 209.0)
po =  Element("Polonium", "Po", 209.0)
at =  Element("Astatine", "At", 210.0)
rn =  Element("Radon", "Rn", 222.0)
fr =  Element("Francium", "Fr", 223.0)
ra =  Element("Radium", "Ra", 226.0)
ac =  Element("Actinium", "Ac", 227.0)
th =  Element("Thorium", "Th", 232.0)

pa =  Element("Protactinium", "Pa", 231.0)
u =  Element("Uranium", "U", 238.0)
np =  Element("Neptunium", "Np", 237.0)
pu =  Element("Plutonium", "Pu", 244.0)
am =  Element("Americium", "Am", 243.0)
cm =  Element("Curium", "Cm", 247.0)
bk =  Element("Berkelium", "Bk", 247.0)
cf =  Element("Californium", "Cf", 251.0)
es =  Element("Einsteinium", "Es", 252.0)
fm =  Element("Fermium", "Fm", 257.0)

md =  Element("Mendelevium", "Md", 258.0)
no =  Element("Nobelium", "No", 259.0)
lr =  Element("Lawrencium", "Lr", 262.0)
rf =  Element("Rutherfordium", "Rf", 267.0)
db =  Element("Dubnium", "Db", 268.0)
sg =  Element("Seaborgium", "Sg", 271.0)
bh =  Element("Bohrium", "Bh", 272.0)
hs =  Element("Hassium", "Hs", 270.0)
mt =  Element("Meitnerium", "Mt", 276.0)
ds =  Element("Darmstadtium", "Ds", 281.0)

rg =  Element("Roentgenium", "Rg", 282.0)
cn =  Element("Copernicium", "Cn", 285.0)
nh =  Element("Nihonium", "Nh", 286.0)
fl =  Element("Flerovium", "Fl", 289.0)
mc =  Element("Moscovium", "Mc", 290.0)
lv =  Element("Livermorium", "Lv", 293.0)
ts =  Element("Tennessine", "Ts", 294.0)
og =  Element("Oganesson", "Og", 294.0)
